import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Starter from "@/components/ui/starter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Observer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#0e0101] relative`}>
        <Starter />
        {children}
      </body>
    </html>
  );
}
